### ISSUE TITLE
ClassNotFoundException on DQL when cache is present

### ISSUE THREAD

**Issue by perk11** [doctrine/DoctrineCacheBundle#28] opened 2014-12-05 12:00 UTC
I first got this issue after updating to 1.0.1, then I reverted to 1.0.0 and it disappeared. Then I updated back to 1.0.1 and can't repeat it anymore, but it persisted after removing `vendor` folder and doing `composer install`, I'm not sure what has changed since.

This only happened in dev environment.

I've started to get this error in getResult() method on DQL-query: 

    Attempted to load class "SubCategory" from namespace "Proxies\__CG__\ProjectName\MainBundle\Entity".

I found two things that temporary fixed this issue:
 
1. Removing annotations cache, particularly one cache file (its contents below)
2. Removing a JOIN of entity that was in this file (ProductImage) from DQL query
       
But every time this cache file was regenerated, error repeated, This is what was in the file:

    <?php return unserialize('a:2:{i:0;O:27:"Doctrine\\ORM\\Mapping\\Entity":2:{s:15:"repositoryClass";N;s:8:"readOnly";b:0;}i:1;O:26:"Doctrine\\ORM\\Mapping\\Table":5:{s:4:"name";s:14:"product_images";s:6:"schema";N;s:7:"indexes";N;s:17:"uniqueConstraints";N;s:7:"options";a:0:{}}}');

Entity `ProductImage` was not directly related to `SubCategory`, only via `Product` entity, in repository of which this error happened.

I use php 5.5.14 on Windows 8 x64

I hope this might help somehow, if no, feel free to close the issue, since I'm not able to repeat it anymore.

**Comment by guilhermeblanco** [comment] 2015-02-01 04:57
This looks like a possible cache glitch by your server.
Closing, since I'm not able to reproduce.

**Closed by guilhermeblanco** 2015-02-01 04:57 UTC
