### ISSUE TITLE
Persistent connections exhaust connections to memcached server

### ISSUE THREAD

**Issue by OndraM** [doctrine/DoctrineCacheBundle#100] opened 2016-09-05 13:17 UTC
Hi,
when persistent connection to memcached is used, it behaves incorrectly and creates more and more **persistent** connections to memcached, which may lead to memcache connection limit exhausting in a short while.

The problem was introduced in #83 with version 1.3.0.

The issue is in [`MemcachedDefinition`](https://github.com/doctrine/DoctrineCacheBundle/blob/master/DependencyInjection/Definition/MemcachedDefinition.php#L53):

```
        if (isset($config['persistent_id']) === true) {
            $connDef->addrgument($config['persistent_id']);
        }

        foreach ($config['servers'] as $host => $server) {
            $connDef->addMethodCall('addServer', array($host, $server['port']));
        }
```

The `addMethodCall('addServer', ...)` adds new server(s) to the connection pool. This is not a problem without the persistent connection, because the pool is created only for the one request and the connection is closed shortly afterwards.

However, when the connection is created as persistent, servers are added to **already existing pool**, so after a while, you ends with many (same) memcached servers in the connection pool and new persistent connection being created to them every time new server from the pool is chosed. As the connections are created as persistent and new servers are added every request, it easily reaches almost any  connection limit the memcached server has.

The addServer() should be IMHO called only if the Memcached instance does not contain the server setup yet (eg. `count($memcached->getServerList())` is 0).

**Comment by alcaeus** [comment] 2018-11-09 05:45
> The addServer() should be IMHO called only if the Memcached instance does not contain the server setup yet.

This isn't all that easy, since we create the service and the calls are only executed when the service is instantiated. I'm not sure why the `\Memcached` class allows adding a server to the pool multiple times, this definitely sounds like a bug in the extension. I'd expect the following code to only produce two connections, not three:
```
$connection = new \Memcached();
$connection->addServer('localhost:123');
$connection->addServer('localhost:234');
$conncetion->addServer('localhost:123');
```

The only way we could fix this is by extending the `\Memcached` class and adding that logic ourselves, which I'd only consider an option if this is indeed confirmed to be wanted behaviour by the memcached extension.

**Comment by fredericch** [comment] 2018-11-17 10:38
Actually it is not a bug. When you have persistent connection, you should only add your servers once. See the first user comment here: http://php.net/manual/en/memcached.construct.php

**Comment by OndraM** [comment] 2018-11-19 11:20
True, I also believe this is not a bug of the memcached extension, but incorrect behavior of the Cache Bundle.

**Comment by OndraM** [comment] 2018-11-19 11:23
True, I also believe this is not a bug of the memcached extension, but incorrect behavior of the Cache Bundle.

See also other comments in the manual, like [this one](http://php.net/manual/en/memcached.construct.php#102487):
> (...) This is why you do not want to call ->addServers() every time your script runs, because ->addServers() does not check for dups and will add hundreds or thousands of connections to the memcached daemon proc from the Apache proc(s).

It is also documented behavior in [the manual](http://php.net/manual/en/memcached.addserver.php):
>  The same server may appear multiple times in the server pool, because no duplication checks are made.

**Comment by alcaeus** [comment] 2018-12-04 06:38
Thanks for confirming this. I'll see if I can come up with a workaround.

**Comment by alcaeus** [comment] 2019-05-29 07:28
Closing here for the reason stated in #156.

**Closed by alcaeus** 2019-05-29 07:28 UTC
Labels: Won't Fix
