### ISSUE TITLE
file_system type does not recognize directory option

### ISSUE THREAD

**Issue by nimasdj** [doctrine/DoctrineCacheBundle#38] opened 2015-01-12 16:27 UTC
When cache "type" is set to "file_system", it gives error for unrecognized "directory" option.

**Comment by stof** [comment] 2015-01-12 16:36
can you show how your config looks like ?

**Comment by nimasdj** [comment] 2015-01-12 18:13
Hi Christophe,
Sure. here it is. It does not recognize "extension" as well. Did I do a mistake?

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                    driver:   "%database_driver%"
                    host:     "%database_host%"
                    port:     "%database_port%"
                    dbname:   "%database_name%"
                    user:     "%database_user%"
                    password: "%database_password%"
                    charset:  UTF8
                    # if using pdo_sqlite as your database driver:
                    #   1. add the path in parameters.yml
                    #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
                    #   2. Uncomment database_path in parameters.yml.dist
                    #   3. Uncomment next line:
                    #     path:     "%database_path%"
                    mapping_types:
                                  enum: string
    orm:
        auto_generate_proxy_classes: false
        proxy_namespace: Proxies
        proxy_dir: includes/doctrine/Proxies
        default_entity_manager: default # The first defined is used if not set
        entity_managers:
            default:
                    connection: default
                    auto_mapping: false
                    metadata_cache_driver: 
                                          type: file_system
                                          directory: includes/doctrine/Cache
                    query_cache_driver:
                                       file_system: ~
                    mappings: # Required
                             ApplicationCommonBundle:
                                                 is_bundle: false
                                                 dir: includes/doctrine/Entities
                                                 prefix: Entities
                                                 type: staticphp
                    class_metadata_factory_name: Doctrine\ORM\Mapping\ClassMetadataFactory
                    default_repository_class:  Doctrine\ORM\EntityRepository
                    dql:
                        datetime_functions:
                                           MONTH: Application\UserBundle\DoctrineExtensions\Query\Mysql\Month
                                           FROM_UNIXTIME: Application\UserBundle\DoctrineExtensions\Query\Mysql\FromUnixtime
                                           UNIX_TIMESTAMP: Application\UserBundle\DoctrineExtensions\Query\Mysql\UnixTimestamp

**Comment by nimasdj** [comment] 2015-01-12 18:21
Sorry, it seems github does not support indent. please see this one:
https://docs.google.com/document/d/1HZ5z3Pa8HVPylUTycmQAneYIT6DP8WJwDorVoTYnR7A/edit?usp=sharing

**Comment by stof** [comment] 2015-01-12 18:30
It does when you use a Markdown code-block

**Comment by stof** [comment] 2015-01-12 18:31
Your config is not configuring the cache directly in the DoctrineCacheBundle configuration but through the older configuration in DoctrineBundle, which does not support all options

**Comment by nimasdj** [comment] 2015-01-12 18:37
Please advice how my config should be instead?

**Comment by nimasdj** [comment] 2015-01-12 18:59
I removed that part from doctrine extension above, and following the docs I added this to config.yml and still getting unrecognized directory option. please advice.

```
doctrine_cache:
    providers:
              metadata_cache_driver: 
                                    type: file_system
                                    directory: includes/doctrine/Cache
              query_cache_driver:
                                 file_system: ~
```

**Comment by nimasdj** [comment] 2015-01-12 19:19
I also used this:

```
doctrine_cache:
    providers:
              metadata_cache_driver: 
                                    file_system:
                                                directory: includes/doctrine/Cache
              query_cache_driver:
                                 file_system: ~
```

This time I don't get error, but no cache file is created in that directory. As these are metadata and query cache driver I don't think I should use $container->get(), please advice what else do I need to do?

**Comment by FabioBatSilva** [comment] 2015-01-12 19:32
Try this :

```yml
doctrine_cache:
  providers:
    metadata_cache:
      file_system:
        directory: "includes/doctrine/Cache"
    query_cache:
       file_system: ~

orm:
    # ...
    entity_managers:
      default:
        connection: default
        auto_mapping: false
        metadata_cache_driver:
          cache_provider: metadata_cache
        query_cache_driver:
          cache_provider: query_cache
```

**Comment by nimasdj** [comment] 2015-01-12 19:41
Thanks for trying help. I get this error:

```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  The service "doctrine.orm.default_entity_manager" has a dependency on a non
  -existent service "doctrine.orm.default_query_cache".
```

And of course doctrine_cache: is before doctrine: in config.yml. please help.

**Comment by nimasdj** [comment] 2015-01-13 07:26
I tried this too and the same error. Do you confirm it as a bug?

```
doctrine_cache:
  providers:
    metadata_cache:
      file_system:
        directory: "includes/doctrine/Cache"
    query_cache:
       file_system: ~

        entity_managers:
            default:
                    connection: default
                    auto_mapping: false
                    metadata_cache_driver:
                                          cache_provider: doctrine_cache.providers.metadata_cache
```

**Comment by nimasdj** [comment] 2015-01-13 16:39
I moved metadata_cache_driver: from "default:" area to entity_managers: area and this time I got:
```
  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException] 
  Unrecognized options "cache_provider" under "doctrine.orm.entity_managers.m   
  etadata_cache_driver"    
```
please advice.

**Comment by nimasdj** [comment] 2015-01-14 14:11
@stof please read my answers after Fabio's post. I appreciate your advice.

**Comment by pkruithof** [comment] 2015-01-15 15:51
The problem is that in the DoctrineExtension class the `setMetadataCacheImpl` call is using a fixed service pattern:

```php
$methods = [
    'setMetadataCacheImpl' => new Reference(sprintf('doctrine.orm.%s_metadata_cache', $entityManager['name']))
];
```

Hence the missing service error. This workaround works for me:

```yaml
doctrine_cache:
  providers:
    metadata_cache:
      aliases: [doctrine.orm.default_metadata_cache]
      file_system:
        directory: "%kernel.cache_dir%/doctrine/metadata"

  orm:
    metadata_cache_driver:
      cache_provider: metadata_cache
```

It seems that either the alias should be added by the Doctrine (cache) bundle, or the method call should have the cache_provider service id injected, or something.

**Comment by stof** [comment] 2015-01-15 15:54
looks like the implementation of the ``cache_provider`` option in DoctrineBundle is buggy actually

**Comment by nimasdj** [comment] 2015-01-15 15:55
@stof when a patch will be released?

**Comment by pkruithof** [comment] 2015-01-15 16:03
I found a bug in DoctrineBundle that's possibly causing this:

https://github.com/doctrine/DoctrineBundle/blob/master/DependencyInjection/DoctrineExtension.php#L696

I'm guessing this needs to be `sprintf`, as now it's outputting the actual service id to my console when I warm up the cache.

It does not completely fix the problem though, it creates an alias named `doctrine.orm.metadata_cache`, whereas the service that is being referenced is named `doctrine.orm.default_metadata_cache`.

**Comment by nimasdj** [comment] 2015-01-15 23:41
@pkruithof You approach works, I added it for both query and metadata cache but it is printed too:
```
doctrine_cache.providers.metadata_cache
doctrine_cache.providers.query_cache
```
Does the DoctrineBundle or DoctrineCacheBundle has a print() command too?

PS.
@stof @Ocramius

**Comment by pkruithof** [comment] 2015-01-16 08:29
@nimasdj you could write a PR which fixes the `sprintf` call, to speed things up. It's a minor change.

**Comment by nimasdj** [comment] 2015-01-16 09:19
@pkruithof I can do that, but it does not drop the need to set aliases as you suggested. what else should be done to remove the obligatory need of aliases?

**Comment by pkruithof** [comment] 2015-01-16 10:02
You can ask the Doctrine(Bundle) people that. My point was rather than asking for a patch you can contribute to the project by creating your own. That's the fastest way to fix this, and you're making others happy in the process :)

**Comment by nimasdj** [comment] 2015-01-16 19:22
I did change it to sprint() but with your snippet I am still getting error. can you show your full test method?

**Comment by guilhermeblanco** [comment] 2015-02-01 04:58
Issue was in DoctrineBundle and got fixed 15 days ago. Closing.

**Closed by guilhermeblanco** 2015-02-01 04:58 UTC
