### ISSUE TITLE
Connections not closed during tests

### ISSUE THREAD

**Issue by EmmanuelVella** [doctrine/DoctrineCacheBundle#50] opened 2015-03-20 18:40 UTC
I have a lot of behat features and I when using ``RedisCache``, the number of connections to redis keep increasing until I get ``Too many open files``.

**Comment by stof** [comment] 2015-03-20 18:43
The issue is actually not long running scripts. It is about closing all connections on shutdown.

I think https://github.com/symfony/symfony/issues/13448 might help in most cases though (i.e. as long as you avoid cyclic references in your object graphs)

**Comment by EmmanuelVella** [comment] 2015-03-20 18:53
Ok, I have updated the title of the issue ;)

Do you think there is a solution until your proposal is implemented ?

**Comment by mikeSimonson** [comment] 2016-04-01 10:26
@EmmanuelVella Is your issue fixed by that feature that is now implemented ?

**Comment by mikeSimonson** [comment] 2016-04-01 10:26
@EmmanuelVella Closing as it's not a bug from the doctrineCacheBundle

**Closed by mikeSimonson** 2016-04-01 10:26 UTC
